#include "aligner/greedy_aligner.hpp"
#include "./utils.hpp"

int main() {

    using namespace seqan3::literals;
    greedy_aligner<128> ga(3, 2, 5);
    ga.align("TGCGTCGCAGTGTCGAAAAAAATCTAAAGGGCCTACCGGGCCCCTTCATGAAGAGCAGGGAAAGAATCTCTATACTATTACTAATGGAAAGCAGTCTTGG"_dna4,
             "TGCGTCGCAGTGTCGAAATAAAATCTAAAGGGCCTACCGGGCCCCTTCATGAAGAGTAGGTAAAGAATCTCTAGTACTACTACTAATGGAAAGCAGTCTTGG"_dna4);
    return 0;
}