#include "aligner/greedy_aligner.hpp"
#include "./utils.hpp"

int main() {

    using namespace seqan3::literals;
    greedy_aligner<160> ga(3, 2, 5, true);
    ga.align("TGATTTATACTTGGTTCAATAAACACCTGTAAACCCCGCAGATATGGAGGAGTGACCGTATATTTATATTATGAAAGATGATGTGTTGATATGTGTCCCCATGGAGATGAGACTAACAAGGCCTATGATTCTACAAATGTTTCATTGTGG"_dna4,
             "TGATTTATACTTGGTTCAATAAACACCTGTAAACCCCGCAGATATGGAGGAGTGACCGTGTATTTATATTATGAAAGATTATGTGTTGATATGTGTCCCCATGGAGATGAGACTAACAAGGTCTATGATTCTACAAATGTTTCATTGTGG"_dna4);
    return 0;
}
